spring:
  application:
    name: listener-sqs
  threads:
    virtual:
      enabled: true
sqs-contrato:
  queue-url: "https://sqs.sa-east-1.amazonaws.com//sqs"
  wait-time-seconds: 20
  visibility-timeout-seconds: 80

brasil-api:
  base-url: https://brasilapi.com.br/api/cep/v2
  connect-timeout-ms: 1500
  response-timeout-ms: 6000
server:
  port: 8081


management:
  statsd:
    metrics:
      export:
        host: ${DD_AGENT_HOST}
        flavor: datadog
        port: 8125
        enabled: ${STATSD_ENABLED:false}
        buffered: true
        max-packet-length: 1400
        polling-frequency: 10s
        publish-unchanged-meters: true
        step: 1m
        protocol: udp
